{{- if .Values.postgresIngress.enabled }}
{{- if eq .Values.postgresIngress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "openg2p.fullname" . }}-postgres
  labels:
    {{- include "openg2p.labels" . | nindent 4 }}
spec:
  selector:
    {{ toYaml .Values.postgresIngress.istioControllerLabel | nindent 4 }}
  servers:
  - port:
      number: {{ .Values.postgresIngress.port }}
      name: tcp-postgres
      protocol: tcp
    hosts:
      - "*"
{{- end }}
{{- end }}
