{{- if .Values.postgresIngress.enabled }}
{{- if eq .Values.postgresIngress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "openg2p.fullname" . }}-postgres
  labels:
    {{- include "openg2p.labels" . | nindent 4 }}
spec:
  hosts:
  - "*"
  gateways:
    - {{ include "openg2p.fullname" . }}-postgres
  tcp:
  - match:
    - port: {{ .Values.postgresIngress.port }}
    route:
    - destination:
        host: {{ include "openg2p.fullname" . }}-postgresql
        port:
          number: 5432
{{- end }}
{{- end }}
