{{- if .Values.selfServiceIngress.enabled }}
{{- if eq .Values.selfServiceIngress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "openg2p.fullname" . }}-self-service
  labels:
    {{- include "openg2p.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ include "openg2p.selfServiceHostname" . }}
  gateways:
    - {{ .Values.selfServiceIngress.istio.virtualservice.gateway }}
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /my
    - uri:
        prefix: /my/
    - uri:
        exact: /web
    - uri:
        exact: /web/login
    - uri:
        exact: /web/database/selector
    redirect:
      uri: /selfservice
  - match:
    - uri:
        prefix: /serviceprovider
    redirect:
      authority: {{ include "openg2p.serviceProviderHostname" . }}
  - headers:
      request:
        set:
          x-forwarded-host: {{ include "openg2p.selfServiceHostname" . }}
          x-forwarded-proto: https
    route:
    - destination:
        host: {{ include "openg2p.fullname" . }}-odoo
        port:
          number: {{ .Values.odoo.service.port }}
{{- end }}
{{- end }}
