{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "openg2p.fullname" . }}
  labels:
    {{- include "openg2p.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ include "openg2p.adminHostname" . }}
  gateways:
    {{- if not .Values.istio.virtualservice.gateway }}
    - {{ include "openg2p.fullname" . }}
    {{- else }}
    - {{ .Values.istio.virtualservice.gateway }}
    {{- end }}
  http:
  - match:
    - uri:
        exact: /
    redirect:
      uri: /web
  - match:
    - uri:
        prefix: /selfservice
    redirect:
      uri: /selfservice
      authority: {{ include "openg2p.selfServiceHostname" . }}
  - match:
    - uri:
        prefix: /serviceprovider
    redirect:
      uri: /serviceprovider
      authority: {{ include "openg2p.serviceProviderHostname" . }}
  - headers:
      request:
        set:
          x-forwarded-host: {{ include "openg2p.adminHostname" . }}
          x-forwarded-proto: https
    route:
    - destination:
        host: {{ include "openg2p.fullname" . }}-odoo
        port:
          number: {{ .Values.odoo.service.port }}
{{- end }}
{{- end }}