{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "openg2p.fullname" . }}
  labels:
    {{- include "openg2p.labels" . | nindent 4 }}
spec:
  hosts:
  {{- if .Values.istio.virtualservice.host }}
  - {{ .Values.istio.virtualservice.host }}
  {{- else }}
  - {{ .Values.global.hostname }}
  {{- end }}
  gateways:
    {{- if not .Values.istio.virtualservice.gateway }}
    - {{ include "openg2p.fullname" . }}
    {{- else }}
    - {{ .Values.istio.virtualservice.gateway }}
    {{- end }}
  http:
  - match:
    - uri:
        exact: /
    redirect:
      uri: /web
  - match:
    - uri:
        prefix: /selfservice
    redirect:
      uri: /selfservice
      authority:
        {{- if .Values.selfServiceIngress.istio.virtualservice.host }}
        {{ .Values.selfServiceIngress.istio.virtualservice.host }}
        {{- else }}
        {{ .Values.global.selfServiceHostname }}
        {{- end }}
  - match:
    - uri:
        prefix: /serviceprovider
    redirect:
      uri: /serviceprovider
      authority:
        {{- if .Values.serviceProviderIngress.istio.virtualservice.host }}
        {{ .Values.serviceProviderIngress.istio.virtualservice.host }}
        {{- else }}
        {{ .Values.global.serviceProviderHostname }}
        {{- end }}
  - route:
    - destination:
        host: {{ include "openg2p.fullname" . }}-odoo
        port:
          number: {{ .Values.odoo.service.port }}
{{- end }}
{{- end }}