apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
data:
  {{- $files := .Files }}
  {{- range tuple "config.json.template" }}
  {{ . }}: |-
      {{ $files.Get . | nindent 6 }}
  {{- end }}