apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spar.fullname" . }}
  labels:
    {{- include "spar.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spar.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: postgres-checker
          image: jbergknoff/postgresql-client
          command:
          - 'sh'
          - '-c'
          - 'until pg_isready -U $SPAR_CORE_DB_USERNAME -h $SPAR_CORE_DB_HOSTNAME -p ${SPAR_CORE_DB_PORT:-5432} -d ${SPAR_CORE_DB_DBNAME:-spardb}; do sleep 3; done'
          env:
          {{- range $k, $v := .Values.envVars }}
            - name: {{ $k }}
            {{- if and (eq $k "SPAR_CORE_DB_HOSTNAME") (not $v) }}
              value: {{ include "postgresql.v1.primary.fullname" $.Subcharts.postgresql }}
            {{- else }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          {{- range $k, $v := .Values.envVarsFrom }}
            - name: {{ $k }}
            {{- if and (eq $k "SPAR_CORE_DB_PASSWORD") (not $v) }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.v1.primary.fullname" $.Subcharts.postgresql }}
                  key: password
            {{- else }}
              {{- toYaml $v | nindent 14 }}
            {{- end }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $k, $v := .Values.envVars }}
            - name: {{ $k }}
            {{- if and (eq $k "SPAR_CORE_DB_HOSTNAME") (not $v) }}
              value: {{ include "postgresql.v1.primary.fullname" $.Subcharts.postgresql }}
            {{- else if and (eq $k "SPAR_G2P_CONNECT_MAPPER_RESOLVE_SENDER_URL") (not $v) }}
              value: {{ printf "http://%s/callback/mapper" (include "spar.fullname" $) }}
            {{- else if and (eq $k "SPAR_G2P_CONNECT_MAPPER_LINK_SENDER_URL") (not $v) }}
              value: {{ printf "http://%s/callback/mapper" (include "spar.fullname" $) }}
            {{- else if and (eq $k "SPAR_G2P_CONNECT_MAPPER_UPDATE_SENDER_URL") (not $v) }}
              value: {{ printf "http://%s/callback/mapper" (include "spar.fullname" $) }}
            {{- else }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          {{- range $k, $v := .Values.envVarsFrom }}
            - name: {{ $k }}
            {{- if and (eq $k "SPAR_CORE_DB_PASSWORD") (not $v) }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.v1.primary.fullname" $.Subcharts.postgresql }}
                  key: password
            {{- else }}
              {{- toYaml $v | nindent 14 }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.containerPort }}
            failureThreshold: 20
            periodSeconds: 30
            timeoutSeconds: 10
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 60
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
