apiVersion: v2
name: social-payments-account-registry
description: A Helm chart for Social Payments Account Registry
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
- name: sunbird-rc-g2p-mapper-registry
  version: 0.1.0
  repository: file://charts/sunbird-rc-g2p-mapper-registry
  condition: sunbird-rc-g2p-mapper-registry.enabled
