apiVersion: v2
name: odk-central-backend
description: A Helm chart for odk-central-backend.
type: application
version: 1.2.0
appVersion: ""
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
keywords:
  - odk
  - odk-central
  - odk-central-backend
