apiVersion: v2
name: openg2p
description: A Helm chart for OpenG2P Package
type: application
version: 1.2.0
appVersion: "1.2.0"
dependencies:
- name: odk-central-mail
  alias: mail
  version: 1.2.0
  condition: mail.enabled
- name: odoo
  repository: https://charts.bitnami.com/bitnami
  version: 21.6.5
  condition: odoo.enabled
