apiVersion: v2
name: openg2p
description: A Helm chart for OpenG2P PBMS Package
type: application
version: 1.2.0
appVersion: "1.2.0"
dependencies:
- name: mail
  version: 1.2.0
  condition: mail.enabled
- name: odoo
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 21.6.5
  condition: odoo.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
