apiVersion: v2
name: G2P Bridge
description: A Helm chart for OpenG2P G2P Bridge
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.x.x
  condition: redis.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
