apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-redis-cache
  labels:
    app.kubernetes.io/name: {{ include "common.names.fullname" . }}-redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.fullname" . }}-redis-cache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.names.fullname" . }}-redis-cache
    spec:
      containers:
        - name: redis-cache
          image: redis:5
          imagePullPolicy: IfNotPresent
          command: 
          - redis-server
          - /usr/local/etc/redis/mnt/redis-enketo-cache.conf
          volumeMounts:
          - name: redis-conf
            mountPath: /usr/local/etc/redis/mnt
      volumes:
        - name: redis-conf
          configMap:
            name: enketo-redis
