apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
type: Opaque
data:
  enketo-secret: |-
    {{ randAlphaNum 64 | b64enc | nindent 4 }}
  enketo-less-secret: |-
    {{ randAlphaNum 32 | b64enc | nindent 4 }}
  enketo-api-key: |-
    {{ randAlphaNum 128 | b64enc | nindent 4 }}