replicaCount: 1

service:
  type: ClusterIP
  port: 8005

image:
  registry: docker.io
  repository: openg2p/odk-central-enketo
  tag: v2023.1.0
  pullPolicy: Always

containerPort: 8005

startupProbe:
  enabled: true
  tcpSocket:
    port: 8005
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1

livenessProbe:
  enabled: true
  tcpSocket:
    port: 8005
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  enabled: true
  tcpSocket:
    port: 8005
  initialDelaySeconds: 0
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

command: []
args: []

resources:
  limits: {}
  #   cpu: 200m
  #   memory: 256Mi
  requests: {}
  #   cpu: 100m
  #   memory: 1500Mi

containerSecurityContext:
  enabled: false
  runAsUser: odk
  runAsNonRoot: true

podSecurityContext:
  enabled: false
  fsGroup: 1001

extraEnvVars: []

extraEnvVarsCM: []

extraEnvVarsSecret: []

# domain: "example.com"
domain: ""
# httpsPort: "443"
httpsPort: ""
# supportEmail: "admin@example.com"
supportEmail: ""
