apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mapper.fullname" . }}
  labels:
    {{- include "mapper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mapper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mapper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mapper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REGISTRY_URL
              {{- if .Values.envVars.REGISTRY_URL }}
              value: {{ .Values.envVars.REGISTRY_URL | quote }}
              {{- else }}
              value: {{ printf "http://%s/" (include "registry.fullname" .Subcharts.registry) }}
              {{- end }}
            - name: CALLBACK_SERVICE_URL
              {{- if .Values.envVars.CALLBACK_SERVICE_URL }}
              value: {{ .Values.envVars.CALLBACK_SERVICE_URL | quote }}
              {{- else }}
              value: {{ printf "http://%s-callback-service/" (include "mapper.fullname" .) }}
              {{- end }}
          {{- range $k, $v := .Values.envVars }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          {{- range $k, $v := .Values.envVarsFrom }}
            - name: {{ $k }}
              {{- toYaml $v | nindent 14 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v0.1.0/docs/swagger.json
              port: {{ .Values.containerPort }}
            failureThreshold: 20
            periodSeconds: 30
            timeoutSeconds: 10
            initialDelaySeconds: 30
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
