apiVersion: v2
name: openg2p-social-registry
description: A Helm chart for OpenG2P Social Registry Module
type: application
version: 1.2.0
appVersion: "1.2.0"
dependencies:
- name: odoo
  repository: https://charts.bitnami.com/bitnami
  version: 21.6.5
  condition: odoo.enabled
