apiVersion: v2
name: OpenG2P Social Registry
description: A Helm chart for OpenG2P Social Registry
type: application
version: 1.2.0
appVersion: "1.2.0"
dependencies:
- name: odoo
  repository: https://charts.bitnami.com/bitnami
  version: 21.6.5
  condition: odoo.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
