global:
  hostname: "openg2p.sandbox.net"
  mailname: "openg2p.sandbox.net"

odoo:
  image:
    repository: openg2p/openg2p-social-registry-odoo-package
    tag: "17.0-develop-social-registry"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  odooEmail: admin@{{ .Values.global.mailname }}

  postgresql:
    enabled: true
    primary:
      extendedConfiguration: |-
        wal_level = logical
        max_wal_senders = 20
        max_replication_slots = 10

  livenessProbe:
    enabled: false

  extraEnvVars:
  - name: ODOO_SKIP_MODULES_UPDATE
    value: "yes"
  - name: LIMIT_TIME_REAL
    value: "5000"
  - name: LIST_DB
    value: "False"
  - name: SERVER_WIDE_MODULES
    value: web,queue_job
  # not using bitnami smtpHost and smtpPort variables, because they need user and pass as well.
  - name: ODOO_SMTP_HOST
    value: "social-registry-mail"
  - name: ODOO_SMTP_PORT_NUMBER
    value: "25"
  - name: LOG_HANDLER
    value: "[':DEBUG']"
  - name: LOG_DB
    value: "True"

mail:
  enabled: true

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "istio-system/all-hosts"
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    tls:
      enabled: true
      mode: SIMPLE
      credentialName: ""
