global:
  hostname: openg2p.sandbox.net
registry:
  enabled: true
  envVars:
    connectionInfo_uri: "" # leave blank to use default postgres
    connectionInfo_username: sunbirdrcuser
    elastic_search_connection_url: "" # leave blank to use default elasticsearch

  envVarsFrom:
    connectionInfo_password: {}
    # leave blank to use default
    # connectionInfo_password:
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgresql
    #       key: password

service:
  type: ClusterIP
  port: 80

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "istio-system/all-hosts"
    prefix: "/registry"
    rewriteUri: "/"
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    tls:
      enabled: true
      mode: SIMPLE
      credentialName: ""

postgresql:
  enabled: true
  auth:
    username: sunbirdrcuser
    database: registry
  primary:
    extendedConfiguration: |-
      wal_level = logical
      max_wal_senders = 20
      max_replication_slots = 10

elasticsearch:
  enabled: true
  image:
    repository: bitnami/elasticsearch
    tag: 7.10.2-debian-10-r350

  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0