{{- if .Values.istio.enabled  }}
{{- if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.fullname" . }}
spec:
  selector:
    {{ toYaml .Values.istio.gateway.ingressController | nindent 4 }}
  servers:
  - port:
      name: http2
      number: 8080
      protocol: HTTP2
    hosts:
      {{- if .Values.istio.gateway.host }}
      - {{ .Values.istio.gateway.host }}
      {{- else }}
      - {{ .Values.global.hostname }}
      {{- end }}
    {{- if .Values.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
      {{- if .Values.istio.gateway.host }}
      - {{ .Values.istio.gateway.host }}
      {{- else }}
      - {{ .Values.global.hostname }}
      {{- end }}
    {{- if .Values.istio.gateway.tls.enabled }}
    tls:
      {{ toYaml (omit .Values.istio.gateway.tls "enabled") | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
