{{- if .Values.postgresIngress.enabled }}
{{- if eq .Values.postgresIngress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: odk-central-postgres
  labels:
    app.kubernetes.io/name: odk-central
spec:
  hosts:
  - "*"
  gateways:
    - odk-central-postgres
  tcp:
  - match:
    - port: {{ .Values.postgresIngress.port }}
    route:
    - destination:
        host: postgres
        port:
          number: 5432
{{- end }}
{{- end }}
