{{- if .Values.postgresIngress.enabled }}
{{- if eq .Values.postgresIngress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "common.names.fullname" . }}-postgresql
  labels:
    app.kubernetes.io/name: {{ include "common.names.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
    - {{ include "common.names.fullname" . }}-postgres
  tcp:
  - match:
    - port: {{ .Values.postgresIngress.port }}
    route:
    - destination:
        host: postgres
        port:
          number: 5432
{{- end }}
{{- end }}
