{{- if .Values.postgresIngress.enabled }}
{{- if eq .Values.postgresIngress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" . }}-postgresql
  labels:
    app.kubernetes.io/name: {{ include "common.names.fullname" . }}
spec:
  selector:
    {{ toYaml .Values.postgresIngress.istioControllerLabel | nindent 4 }}
  servers:
  - port:
      number: {{ .Values.postgresIngress.port }}
      name: tcp-postgres
      protocol: tcp
    hosts:
      - "*"
{{- end }}
{{- end }}
