{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: odk-central
  labels:
    app.kubernetes.io/name: odk-central
spec:
  hosts:
  {{- if .Values.istio.virtualservice.host }}
  - {{ .Values.istio.virtualservice.host }}
  {{- else }}
  - {{ .Values.global.hostname }}
  {{- end }}
  gateways:
    {{- if not .Values.istio.virtualservice.gateway }}
    - odk-central
    {{- else }}
    - {{ .Values.istio.virtualservice.gateway }}
    {{- end }}
  http:
  - route:
    - destination:
        host: {{ .Values.istio.virtualservice.destination }}
        port:
          number: {{ .Values.istio.virtualservice.destinationPort }}
{{- end }}
{{- end }}
