global:
  hostname: "odk.openg2p.sandbox.net"
  mailname: "openg2p.sandbox.net"
  httpsPort: "443"
  sysAdminEmail: "admin@odk.openg2p.sandbox.net"

odk-central-mail:
  enabled: true
  fullnameOverride: mail
odk-central-pyxform:
  enabled: true
  fullnameOverride: pyxform
odk-central-enketo:
  enabled: true
  fullnameOverride: enketo
odk-central-backend:
  enabled: true
  fullnameOverride: service
odk-central-frontend:
  enabled: true
  fullnameOverride: nginx

ingress:
  enabled: false
  ingressClassName: ""
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: ""
  annotations: {}
  tls: false
  selfSigned: false
  extraPaths: []
  extraTls: []
  secrets: []

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "istio-system/all-hosts"
    destination: "nginx"
    destinationPort: "80"
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    tls:
      enabled: true
      mode: SIMPLE
      credentialName: ""

postgresIngress:
  enabled: true
  type: istio # Define for type ingress
  # host not need. Because tcp.
  istioControllerLabel:
    istio: ingressgateway
  port: 5433

