global:
  # hostname name of installation
  odkHostname: "odk.openg2p.sandbox.net"
  # mail name
  mailname: "openg2p.sandbox.net"
  # system admin email
  sysAdminEmail: "admin@odk.openg2p.sandbox.net"
  # Support email
  supportEmail: "support@odk.openg2p.sandbox.net"

odk-central-mail:
  enabled: true
odk-central-pyxform:
  enabled: true
odk-central-enketo:
  enabled: true
odk-central-backend:
  enabled: true
  postgresql:
    nameOverride: odk-central-postgresql
odk-central-frontend:
  enabled: true
