global:
  # hostname name of installation
  # hostname: "odk.example.com"
  hostname: "odk.openg2p.sandbox.net"
  # mail name
  mailname: "openg2p.sandbox.net"
  # system admin email
  # sysAdminEmail: "admin@example.com"
  sysAdminEmail: "admin@odk.openg2p.sandbox.net"
  # Support email
  # supportEmail: "support@example.com"
  supportEmail: "support@odk.openg2p.sandbox.net"

odk-central-mail:
  enabled: true
odk-central-pyxform:
  enabled: true
odk-central-enketo:
  enabled: true
odk-central-backend:
  enabled: true
odk-central-frontend:
  enabled: true

ingress:
  enabled: false
  ingressClassName: ""
  pathType: ImplementationSpecific
  pathBackend: '{{ include "common.names.fullname" . }}-odk-central-frontendend'
  apiVersion: ""
  hostname: ""
  annotations: {}
  tls: false
  selfSigned: false
  extraPaths: []
  extraTls: []
  secrets: []

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "internal"
    destination: '{{ include "common.names.fullname" . }}-odk-central-frontendend'
    destinationPort: "80"
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    tls:
      enabled: true
      mode: SIMPLE
      credentialName: ""

postgresIngress:
  enabled: false
  type: istio # Define for type ingress
  # host not need. Because tcp.
  istioControllerLabel:
    istio: ingressgateway
  port: 5433
